SCRIPT=$(realpath -s "$0")
PERF_BASE_PATH=$(dirname "$SCRIPT")

cd $PERF_BASE_PATH/pplnn

rm -rf pplnn-build
 
PPL_BUILD_THREAD_NUM=32 bash build.sh -DPPLNN_HOLD_DEPS=ON  -DPPLNN_USE_LLM_CUDA=ON -DPPLNN_CUDA_ENABLE_NCCL=ON -DPPLNN_ENABLE_CUDA_JIT=OFF -DPPLNN_CUDA_ARCHITECTURES="'80;86;87'" -DPPLCOMMON_CUDA_ARCHITECTURES="'80;86;87'" -DPPLNN_ENABLE_KERNEL_PROFILING=OFF
